version: 2
jobs:
  # TODO: Monorepo support - only run tests on projects if they have changed
  # e.g. https://discuss.circleci.com/t/does-circleci-2-0-work-with-monorepos/10378/14

  test-graphql:
    docker:
      - image: metaspace2020/sm-webapp:0.11

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

    working_directory: ~/metaspace/metaspace/graphql
    steps:
      - checkout:
          path: ~/metaspace
      - restore_cache:
          keys:
            - graphql-yarn-cache-{{checksum "yarn.lock"}}
      - run:
          name: Install npm packages
          command: |
            yarn install --frozen-lockfile
            yarn global add codecov
      - save_cache:
          key: graphql-yarn-cache-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
      - run:
          name: Run tests
          command: |
            mkdir -p /opt/data/metaspace/public/
            psql -h localhost -U sm -c "CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres'"
            psql -h localhost -U sm -c "CREATE DATABASE sm_test owner sm"
            psql -h localhost -U sm -d sm_test -c "CREATE EXTENSION \"uuid-ossp\";"
            psql -h localhost -U sm -d sm_test -c "CREATE SCHEMA graphql;"
            yarn run gen-binding
            yarn run deref-schema
            NODE_ENV=test yarn run test-ci --verbose --detectOpenHandles --forceExit
      - run:
          name: Upload coverage
          command: |
            yarn run test-ci --coverage
            npx codecov -p ../.. -F graphql


  generate-graphql-schema:
    docker:
      - image: metaspace2020/sm-webapp:0.11

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

    working_directory: ~/metaspace/metaspace/graphql
    steps:
      - checkout:
          path: ~/metaspace
      - restore_cache:
          keys:
            - graphql-yarn-cache-{{checksum "yarn.lock"}}
      - run:
          name: Install npm packages
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: graphql-yarn-cache-{{checksum "yarn.lock"}}
          paths:
            - ~/metaspace/metaspace/graphql/node_modules
            - /usr/local/share/.cache/yarn
      - run:
          name: Generate graphql JSON schema
          command: |
            mkdir -p dist
            node ./bin/generate-json-graphql-schema.js ./dist/graphql-schema.json
      - run:
          name: Dump GraphQL and SQL schema
          command: |
            psql -h localhost -U sm -c "CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres'"
            psql -h localhost -U sm -c "CREATE DATABASE sm_test owner sm"
            yarn run gen-binding
            NODE_CONFIG_ENV=test yarn run gen-sql-schema
      - run:
          name: Assert SQL schema doesn't have uncommitted changes
          command: git diff --exit-code ../engine/scripts/db_schema.sql
      - persist_to_workspace:
          root: dist
          paths:
            - graphql-schema.json

  test-webapp:
    docker:
      - image: metaspace2020/sm-webapp:0.11

    working_directory: ~/metaspace/metaspace/webapp
    steps:
      - checkout:
          path: ~/metaspace
      - restore_cache:
          keys:
            - webapp-yarn-cache-{{checksum "yarn.lock"}}
      - run:
          name: Install npm packages
          command: |
            yarn install --frozen-lockfile
            yarn global add codecov
      - save_cache:
          key: webapp-yarn-cache-{{checksum "yarn.lock"}}
          paths:
            - ~/metaspace/metaspace/webapp/node_modules
            - /usr/local/share/.cache/yarn
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Copy configs
          command: |
            cp ci/conf.js .
            cp ci/clientConfig.json src/
      - run:
          name: Compile
          command: |
            yarn run build-ci
      - run:
          name: Run tests
          command: |
            cp ~/workspace/graphql-schema.json ./tests/utils/graphql-schema.json
            yarn run test-ci
      - run:
          name: Upload coverage
          command: |
            yarn run test-ci --coverage --maxWorkers=1
            npx codecov -p ../.. -F webapp
      - run:
          name: Lint code
          command: yarn run lint --max-warnings 0 --no-fix

  test-webapp-e2e:
    docker:
      - image: metaspace2020/sm-webapp:0.11

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

      - image: elasticsearch:5.4.0-alpine
        environment:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        command: [elasticsearch, -Etransport.host=127.0.0.1]

      - image: redis:3.2-alpine

      - image: rabbitmq:3.6-alpine
        environment:
          RABBITMQ_DEFAULT_USER: sm
          RABBITMQ_DEFAULT_PASS: password

    working_directory: ~/metaspace/metaspace/webapp
    steps:
      - checkout:
          path: ~/metaspace
      - restore_cache:
          keys:
            - yarn-cache-{{checksum "yarn.lock"}}-{{checksum "../graphql/yarn.lock"}}
            - yarn-cache
      - run:
          name: Install npm packages
          command: |
            yarn install
            npm rebuild node-sass  # https://github.com/sass/node-sass/issues/1804
            cd ../graphql
            yarn install
      - save_cache:
          key: yarn-cache-{{checksum "yarn.lock"}}-{{checksum "../graphql/yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
      - run:
          name: Build webapp
          command: |
            cp ci/conf.js conf.js
            cp ci/clientConfig.json src/
            yarn run build-ci
      - run:
          name: Start GraphQL server and service mocks
          command: |
            export NPM_CONFIG_LOGLEVEL=warn
            cd ../graphql
            yarn run deref-schema
            cp tests/mock_config.js config/default.js
            forever start -e api_mocks.err.log tests/api_mocks.js
            forever start -o sm-graphql.out.log -e sm-graphql.err.log server.js
      - run:
          name: Load test data into the database and ElasticSearch
          command: |
            cd ci
            bash populate_pg_es.sh
      - run:
          name: Run tests
          command: |
            export NPM_CONFIG_LOGLEVEL=warn
            #while true; do echo '---'; sleep 5; done   # uncomment this line for debugging
            stty cols 80  # https://github.com/DevExpress/testcafe/issues/1469
            yarn run test-e2e

  test-pycode-format:
    docker:
      - image: metaspace2020/sm-engine:1.8.1
    working_directory: ~/metaspace
    steps:
      - checkout:
          path: ~/metaspace
      - run:
          name: Code format check for .py files in ansible and metaspace directories
          command: |
            black --check ansible metaspace/off-sample metaspace/python-client

  test-engine:
    docker:
      - image: metaspace2020/sm-engine:1.8.1

      - image: redis:5.0.3

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

      - image: elasticsearch:5.4.0-alpine
        environment:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        command: [elasticsearch, -Etransport.host=127.0.0.1]

      - image: rabbitmq:3.6-management
        environment:
          RABBITMQ_DEFAULT_USER: sm
          RABBITMQ_DEFAULT_PASS: password

    working_directory: ~/metaspace/metaspace/engine
    steps:
      - checkout:
          path: ~/metaspace
      - run:
          name: Test engine dependencies
          command: |
            pip install --upgrade -r requirements.txt
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run unit and integration tests
          command: |
            #while true; do echo '---'; sleep 5; done   # uncomment this line for debugging
            coverage run --source=./sm/engine --omit=./sm/engine/tests/*,./tests/* \
            -m pytest --tb=short sm/engine/tests tests
      - run:
          name: Upload test coverage
          command: |
            #while true; do echo '---'; sleep 5; done   # uncomment this line for debugging
            codecov --root ../.. -F engine
      - run:
          name: Run linter
          # Limit number of CPUs to prevent silent OOMs in background processes
          # https://github.com/PyCQA/pylint/issues/3899
          command: pylint -j1 sm scripts
      - run:
         name: Run code formatter
         command: black --check .

  test-engine-sci:
    docker:
      - image: metaspace2020/sm-engine:1.8.1

      - image: redis:5.0.3

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

      - image: elasticsearch:5.4.0-alpine
        environment:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        command: [elasticsearch, -Etransport.host=127.0.0.1]

      - image: rabbitmq:3.6-management
        environment:
          RABBITMQ_DEFAULT_USER: sm
          RABBITMQ_DEFAULT_PASS: password

    working_directory: ~/metaspace/metaspace/engine
    steps:
      - checkout:
          path: ~/metaspace
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Test setup
          command: |
            pip install --upgrade -r requirements.txt
            pip install -e .
      - run:
          name: Create engine database
          command: |
            createdb -h localhost -U sm sm_test
            psql -h localhost -U sm -d sm_test < scripts/db_schema.sql
      - run:
          name: Import test molecular database
          command: |
            wget -qN https://sm-engine.s3-eu-west-1.amazonaws.com/tests/hmdb_4.tsv -O /tmp/hmdb_4.tsv
            python scripts/import_molecular_db.py --config=tests/sci_test/config.json \
              HMDB-v4 2020-01-01 /tmp/hmdb_4.tsv
      - run:
          name: Run scientific test
          command: |
            #while true; do echo '---'; sleep 5; done  # uncomment this line for debugging
            python tests/sci_test/spheroid.py -r --mock-img-store --lithops --config=tests/sci_test/config.json

workflows:
  version: 2
  commit:
    jobs:
      - generate-graphql-schema
      - test-pycode-format
      - test-engine:
          requires:
            - generate-graphql-schema
#      - test-engine-sci  # uncomment for debugging
      - test-graphql
      - test-webapp:
          requires:
            - generate-graphql-schema
  sci-test-on-demand:
    jobs:
      - generate-graphql-schema
      - test-engine-sci:
          requires:
            - generate-graphql-schema
          filters:
            branches:
              # Replace this with the branch to run sci-test against
              only: feat/ibm-cloud-dev

## Disabled until we have time to redo these tests
#  daily:
#    jobs:
#      - test-webapp-e2e
#    triggers:
#      - schedule:
#          cron: "0 11 * * 1-5"
#          filters:
#            branches:
#              only:
#                - master
#                - feature/.*
#  weekly:
#    jobs:
#      - generate-graphql-schema
#      - test-engine-sci
#    triggers:
#      - schedule:
#          cron: "0 11 * * 1"
#          filters:
#            branches:
#              only:
#                - master
#
