version: 2
jobs:
  build:
    docker:
      # includes:
      #   - miniconda with all packages required for sm-engine
      #   - pyspark installation
      - image: lomereiter/sm_engine:0.7.1-py3

      - image: postgres:9.5-alpine
        environment:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: password

      - image: elasticsearch:5.4.0-alpine
        environment:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        command: [elasticsearch, -Etransport.host=127.0.0.1]

      - image: rabbitmq:3.6-alpine
        environment:
          RABBITMQ_DEFAULT_USER: sm_test
          RABBITMQ_DEFAULT_PASS: password

    working_directory: /code/sm-engine
    steps:
      - checkout
      - run:
          name: Setup configuration files
          command: |
            cp conf/sm_log.cfg.template conf/sm_log.cfg
            cp docker/sci_test_config.json conf/config.json
            mkdir -p logs
            echo 'localhost:5432:sm:password\n' > ~/.pgpass
            chmod 0600 ~/.pgpass
      - run:
          name: Run unit and integration tests
          command: |
            source docker/env.sh
            pip install pysparkling
            #while true; do echo '---'; sleep 5; done   # uncomment this line for debugging
            coverage run --source=./sm/engine --omit=./sm/engine/tests/*,./tests/* -m py.test sm/engine/tests tests --ignore=tests/test_queue.py --ignore=tests/test_sm_daemon.py && coveralls
      - run:
          name: Create and prefill the database
          command: |
            wget -qN https://s3-eu-west-1.amazonaws.com/embl-sm-testing/dumps/2017-08-09/annotate-moldb.pgdump
            wget -qN https://s3-eu-west-1.amazonaws.com/embl-sm-testing/dumps/2017-08-09/theor_peaks-hmdb.pgdump
            createdb -h localhost -U postgres sm_test
            psql -U sm -h localhost -d sm_test < scripts/create_schema.sql
            pg_restore -a -U sm -h localhost -d sm_test theor_peaks-hmdb.pgdump
            pg_restore -U sm -h localhost --no-owner --role=sm -d sm_test annotate-moldb.pgdump
            cp docker/mol_db_conf.ini /root/sm-molecular-db/conf/local.ini
      - run:
          name: Run scientific test
          command: |
            cd /root/sm-molecular-db
            source activate mol_db
            python app/main.py &  # run in background
            cd /code/sm-engine
            source docker/env.sh
            python tests/sci_test_spheroid.py -r
